### PR TITLE
Current user

### PR DESCRIPTION
**Pull request by a0129998**
added and styled username

### CODE REVIEW

**Comment by a0129998** [comment]
Fixed #44

**Comment by nlzz22** [comment]
image

This is what I see from the website. Can you move the username next to the logout button instead ?

**Comment by a0129998** [comment]
@helloqx can you work on the logout pop up?

**Comment by a0129998** [comment]
@xaterz updated button size, please review.

**Comment by a0129998** [comment]
image

**Comment by xaterz** [comment]
Created Issue #51 for the logout confirmation pop-up. To be implemented in the future.

Can pull this branch into integration and close.

**Pull request merged**
