### PR TITLE
Merge classSizeEnhancement branch into integration branch

### LINKED ISSUE #42: dynamic current sem
currently the current sem for `non-overlapping modules by semester` is hardcoded to be `AY 16/17 SEM 1`. modify it to make the time dynamic

### LINKED ISSUE #57: Find Modules with Specified Class Size feature enhancement
A few things to tweak for the search function:
1. Leaving the AY-Semester field blank can invoke search in the current AY-Semester
2. Leaving the left-interval for class size blank should search for all modules with class size <= right-interval
3. Leaving the right-interval for class size blank should search for all modules with class size >= left-interval

### PR DESCRIPTION
**Pull request by nlzz22**
Fixes #42 
Fixes #57 : NOTE: Please scroll down in this issue to see my comments on what is the actual implementation, as actual implementation is different from initially planned when issue was opened.

Branch: classSizeEnhancement

### CODE REVIEW

**Comment by a0129998** [comment]
issue #42 seems to be in functioning,
1. successfully blocked invalid ranges,
2. successfully blocked negative numbers

**Comment by nlzz22** [comment]
@a0129998 Fixed for modules taken before internship page at commit 689e2a3 . Please review again, thanks

**Comment by nlzz22** [comment]
Considered and implemented what was suggested by @helloqx

**Comment by nlzz22** [comment]
Updated branch with latest from integration, please review again, thank you. @a0129998 @helloqx

**Pull request merged**
